"""add debt_simplification to groups

Revision ID: d9f75a7ac096
Revises: 0001_initial_schema
Create Date: 2026-02-19 19:09:14.702239

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd9f75a7ac096'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('debt_simplification', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'debt_simplification')
    # ### end Alembic commands ###
